cache:
  mount:
    - node_modules
build:
  image: node:wheezy
  commands:
    - npm install --unsafe-perm
    - npm run build

deploy:
  ssh:
    host: hoogit.ca
    user: user
    commands:
      - echo docker restart powerhour-staging
    when:
      branch: develop
  ssh:
    host: hoogit.ca
    user: user
    commands:
      - echo docker restart powerhour
    when:
      branch: master
branches:
  - master
  - develop
